# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  ruby:
    docker:
      - image: cimg/ruby:2.6.6
    resource_class: small

# Shared steps for setup of images
commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: make install
      - save_cache:
            key: v1-bundle-{{ checksum "Gemfile.lock" }}
            paths:
              - vendor/bundle
jobs:
  build:
    executor: ruby
    steps:
      - setup
  test:
    executor: ruby
    steps:
      - setup
      - run: make test
  lint:
    executor: ruby
    steps:
      - setup
      - run: make check

workflows:
  quality:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
